# Generated by Django 5.1 on 2024-12-05 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Neoshop', '0004_cartitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcategory',
            name='category',
            field=models.CharField(max_length=100),
        ),
        migrations.RemoveField(
            model_name='subcategory',
            name='name',
        ),
        migrations.RemoveField(
            model_name='products',
            name='category2',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.AddField(
            model_name='products',
            name='category2',
            field=models.ManyToManyField(related_name='products', to='Neoshop.subcategory'),
        ),
    ]
